// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class SpringTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @Test
    public void spring() throws InterruptedException {
        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(842, 822));
        driver.findElement(By.name("q")).click();
        driver.findElement(By.name("q")).sendKeys("java");
        driver.findElement(By.cssSelector(".sbhl .wM6W7d > span")).click();
        Thread.sleep(10000);
    }
    @After
    public void tearDown() {
        driver.quit();
    }

}



